#!/bin/bash
set -e

CAPPS_USER=capps_user
CAPPS_PASSWORD=capps_pass
PORT=5432
CAPPS_DB=capps_db

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -p $PORT <<-EOSQL
  CREATE ROLE $CAPPS_USER WITH LOGIN PASSWORD '$CAPPS_PASSWORD' CREATEDB;
  CREATE DATABASE $CAPPS_DB OWNER $CAPPS_USER;
  REVOKE ALL PRIVILEGES ON DATABASE $CAPPS_DB FROM PUBLIC;
  GRANT ALL PRIVILEGES ON DATABASE $CAPPS_DB TO $CAPPS_USER;
EOSQL

DEMO_TABLE=demo
psql -v ON_ERROR_STOP=1 --username "$CAPPS_USER" --dbname "$CAPPS_DB" -p $PORT <<-EOSQL
  CREATE TABLE $DEMO_TABLE (A INT, B VARCHAR(100));
EOSQL